#' Add targets infrastructure
#' @description Add targets infrastructure to a project directory
#' @param project_directory the project directory file path
#' @param type project type. Should be one returned by \code{projectTypes()}.
#' @param ... arguments to pass to \code{targetsRun()}
#' @examples
#' \dontrun{
#' projectSkeleton(paste0(tempdir(),'/test_project'))
#' targets(paste0(tempdir(),'/test_project'),type = 'report') 
#' }
#' @export

targets <- function(project_directory,type = projectTypes(),...){
  
  if (missing(type)) {
    type <- 'report'
  }
  
  type <- match.arg(type)
  
  message('Adding targets infrastructure')
  
  targetsScript(project_directory,type)
  targetsPipeline(project_directory,type)
  targetsRun(project_directory,...)
}

scriptHeader <- function(){
  version <- packageVersion('projecttemplates') %>% 
    as.character()
  
  glue('## Generated by projecttemplates (https://jasenfinch.github.io/projecttemplates/) v{version}')
}

#' Add a targets script
#' @description Add a _targets.R script to a project directory
#' @param project_directory the project directory file path
#' @param type project type. Should be one returned by \code{projectTypes()}
#' @examples 
#' \dontrun{
#' projectSkeleton(paste0(tempdir(),'/test_project'))
#' targetsPipeline(paste0(tempdir(),'/test_project'),type = 'report')
#' }
#' @export

targetsScript <- function(project_directory,type = projectTypes()){
  if (missing(type)) {
    type <- 'report'
  }
  
  type <- match.arg(type)
  
  
  
  template <- glue('
{scriptHeader()}

source("R/utils.R")

"R/functions/" %>%
  list.files(full.names = T) %>%
  walk(source)                   

tar_option_set(error = "continue")

')
  
  writeLines(template,str_c(project_directory,'_targets.R',sep = '/'))
}

#' Add a targets pipeline
#' @description Add a targets pipeline to a project directory.
#' @param project_directory the project directory file path
#' @param type project type. Should be one returned by \code{projectTypes()}.
#' @examples
#' \dontrun{
#' projectSkeleton(paste0(tempdir(),'/test_project'))
#' targetsPipeline(paste0(tempdir(),'/test_project'),type = 'report')
#' }
#' @importFrom glue glue
#' @export

targetsPipeline <- function(project_directory,type = projectTypes()){
  
  if (missing(type)) {
    type <- 'report'
  }
  
  type <- match.arg(type)
  
  if (type == 'manuscript') {
    formats <- ',output_format = "all"'
  } else {
    formats <- ''
  }
  
  cmd <- glue('
  ## render {type}
  tar_render(
              {type},
              "{type}/{type}.Rmd",
              output_dir = "exports",
              quiet = TRUE{formats}
  )
              ')
  
  if (type == 'manuscript') {
    cmd <- str_c('
  ## render tables
  tar_render(tables,
             "manuscript/tables.Rmd",
             output_dir = "exports",
             quiet = TRUE),
  
  ## render figures
  tar_render(figures,
             "manuscript/figures.Rmd",
             output_dir = "exports",
             quiet = TRUE),
  
  ## render supplementary information
  tar_render(supplementary,
             "manuscript/supplementary.Rmd",
             output_dir = "exports",
             quiet = TRUE),
                 ',
                 cmd)
  }
  
  p <- glue('
  list(
  {cmd}
  )
  ') %>%
    write(file = str_c(project_directory,'/_targets.R'),
          append = TRUE)
}

#' Add a targets run script to a project directory
#' @description Add a run.R script to a project directory that can be used to trigger building a targets workflow.
#' @param project_directory the project directory file path
#' @param renv add line to script restore package environment using renv
#' @examples 
#' \dontrun{
#' projectSkeleton(paste0(tempdir(),'/test_project'))
#' targetsRun(paste0(tempdir(),'/test_project'))
#' }
#' @export

targetsRun <- function(project_directory,renv = TRUE){
  if (isTRUE(renv)) {
    restore <- 'renv::restore()'
  } else {
    restore <- ''
  }
  script <- glue('
{scriptHeader()}
## Execute this script to run the project analysis
{restore}
targets::tar_make()

pipeline_graph <- targets::tar_visnetwork(label = c("time", "size"))
visNetwork::visSave(pipeline_graph,
                    file = "exports/pipeline_graph.html")
')
  
  writeLines(script,str_c(project_directory,'/run.R'))
}